// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "appengine": dummy-auths Resource Client
//
// Command:
// $ goagen
// --design=github.com/groovenauts/blocks-concurrent-batch-server/design
// --out=$(GOPATH)/src/github.com/groovenauts/blocks-concurrent-batch-server
// --version=v1.3.1

package client

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
)

// CreateDummyAuthsPath computes a request path to the create action of dummy-auths.
func CreateDummyAuthsPath() string {

	return fmt.Sprintf("/dummy-auths")
}

// create
func (c *Client) CreateDummyAuths(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewCreateDummyAuthsRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewCreateDummyAuthsRequest create the request corresponding to the create action endpoint of the dummy-auths resource.
func (c *Client) NewCreateDummyAuthsRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("POST", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}
