// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "appengine": InstanceGroupConstructionTask Resource Client
//
// Command:
// $ goagen
// --design=github.com/groovenauts/blocks-concurrent-batch-server/design
// --out=$(GOPATH)/src/github.com/groovenauts/blocks-concurrent-batch-server
// --version=v1.3.1

package client

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
)

// StartInstanceGroupConstructionTaskPath computes a request path to the start action of InstanceGroupConstructionTask.
func StartInstanceGroupConstructionTaskPath(orgID string, name string) string {
	param0 := orgID
	param1 := name

	return fmt.Sprintf("/orgs/%s/instance_groups/%s/construction_tasks", param0, param1)
}

// Start operation
func (c *Client) StartInstanceGroupConstructionTask(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewStartInstanceGroupConstructionTaskRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewStartInstanceGroupConstructionTaskRequest create the request corresponding to the start action endpoint of the InstanceGroupConstructionTask resource.
func (c *Client) NewStartInstanceGroupConstructionTaskRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("POST", u.String(), nil)
	if err != nil {
		return nil, err
	}
	if c.APIKeySigner != nil {
		if err := c.APIKeySigner.Sign(req); err != nil {
			return nil, err
		}
	}
	return req, nil
}

// WatchInstanceGroupConstructionTaskPath computes a request path to the watch action of InstanceGroupConstructionTask.
func WatchInstanceGroupConstructionTaskPath(orgID string, name string, id string) string {
	param0 := orgID
	param1 := name
	param2 := id

	return fmt.Sprintf("/orgs/%s/instance_groups/%s/construction_tasks/%s", param0, param1, param2)
}

// Watch
func (c *Client) WatchInstanceGroupConstructionTask(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewWatchInstanceGroupConstructionTaskRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewWatchInstanceGroupConstructionTaskRequest create the request corresponding to the watch action endpoint of the InstanceGroupConstructionTask resource.
func (c *Client) NewWatchInstanceGroupConstructionTaskRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("PUT", u.String(), nil)
	if err != nil {
		return nil, err
	}
	if c.APIKeySigner != nil {
		if err := c.APIKeySigner.Sign(req); err != nil {
			return nil, err
		}
	}
	return req, nil
}
