// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "appengine": InstanceGroupConstructingTask Resource Client
//
// Command:
// $ goagen
// --design=github.com/groovenauts/blocks-concurrent-batch-server/design
// --out=$(GOPATH)/src/github.com/groovenauts/blocks-concurrent-batch-server
// --version=v1.3.1

package client

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
)

// WatchInstanceGroupConstructingTaskPath computes a request path to the watch action of InstanceGroupConstructingTask.
func WatchInstanceGroupConstructingTaskPath(id string) string {
	param0 := id

	return fmt.Sprintf("/constructing_tasks/%s", param0)
}

// Watch
func (c *Client) WatchInstanceGroupConstructingTask(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewWatchInstanceGroupConstructingTaskRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewWatchInstanceGroupConstructingTaskRequest create the request corresponding to the watch action endpoint of the InstanceGroupConstructingTask resource.
func (c *Client) NewWatchInstanceGroupConstructingTaskRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("PUT", u.String(), nil)
	if err != nil {
		return nil, err
	}
	if c.APIKeySigner != nil {
		if err := c.APIKeySigner.Sign(req); err != nil {
			return nil, err
		}
	}
	return req, nil
}
