// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "appengine": PipelineBase Resource Client
//
// Command:
// $ goagen
// --design=github.com/groovenauts/blocks-concurrent-batch-server/design
// --out=$(GOPATH)/src/github.com/groovenauts/blocks-concurrent-batch-server
// --version=v1.3.1

package client

import (
	"bytes"
	"context"
	"fmt"
	"net/http"
	"net/url"
)

// ClosePipelineBasePath computes a request path to the close action of PipelineBase.
func ClosePipelineBasePath(id string) string {
	param0 := id

	return fmt.Sprintf("/pipeline_bases/%s", param0)
}

// Close
func (c *Client) ClosePipelineBase(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewClosePipelineBaseRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewClosePipelineBaseRequest create the request corresponding to the close action endpoint of the PipelineBase resource.
func (c *Client) NewClosePipelineBaseRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("PUT", u.String(), nil)
	if err != nil {
		return nil, err
	}
	if c.APIKeySigner != nil {
		if err := c.APIKeySigner.Sign(req); err != nil {
			return nil, err
		}
	}
	return req, nil
}

// CreatePipelineBasePath computes a request path to the create action of PipelineBase.
func CreatePipelineBasePath() string {

	return fmt.Sprintf("/pipeline_bases")
}

// create
func (c *Client) CreatePipelineBase(ctx context.Context, path string, payload *PipelineBasePayload, orgID string, contentType string) (*http.Response, error) {
	req, err := c.NewCreatePipelineBaseRequest(ctx, path, payload, orgID, contentType)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewCreatePipelineBaseRequest create the request corresponding to the create action endpoint of the PipelineBase resource.
func (c *Client) NewCreatePipelineBaseRequest(ctx context.Context, path string, payload *PipelineBasePayload, orgID string, contentType string) (*http.Request, error) {
	var body bytes.Buffer
	if contentType == "" {
		contentType = "*/*" // Use default encoder
	}
	err := c.Encoder.Encode(payload, &body, contentType)
	if err != nil {
		return nil, fmt.Errorf("failed to encode body: %s", err)
	}
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	values := u.Query()
	values.Set("org_id", orgID)
	u.RawQuery = values.Encode()
	req, err := http.NewRequest("POST", u.String(), &body)
	if err != nil {
		return nil, err
	}
	header := req.Header
	if contentType == "*/*" {
		header.Set("Content-Type", "application/json")
	} else {
		header.Set("Content-Type", contentType)
	}
	if c.APIKeySigner != nil {
		if err := c.APIKeySigner.Sign(req); err != nil {
			return nil, err
		}
	}
	return req, nil
}

// DeletePipelineBasePath computes a request path to the delete action of PipelineBase.
func DeletePipelineBasePath(id string) string {
	param0 := id

	return fmt.Sprintf("/pipeline_bases/%s", param0)
}

// delete
func (c *Client) DeletePipelineBase(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewDeletePipelineBaseRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewDeletePipelineBaseRequest create the request corresponding to the delete action endpoint of the PipelineBase resource.
func (c *Client) NewDeletePipelineBaseRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("DELETE", u.String(), nil)
	if err != nil {
		return nil, err
	}
	if c.APIKeySigner != nil {
		if err := c.APIKeySigner.Sign(req); err != nil {
			return nil, err
		}
	}
	return req, nil
}

// HibernationCheckingFinalizeTaskPipelineBasePath computes a request path to the hibernation_checking_finalize_task action of PipelineBase.
func HibernationCheckingFinalizeTaskPipelineBasePath(id string) string {
	param0 := id

	return fmt.Sprintf("/pipeline_bases/%s/hibernation_checking_finalize_task", param0)
}

// Task to finalize hibernation_checking status
func (c *Client) HibernationCheckingFinalizeTaskPipelineBase(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewHibernationCheckingFinalizeTaskPipelineBaseRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewHibernationCheckingFinalizeTaskPipelineBaseRequest create the request corresponding to the hibernation_checking_finalize_task action endpoint of the PipelineBase resource.
func (c *Client) NewHibernationCheckingFinalizeTaskPipelineBaseRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("PUT", u.String(), nil)
	if err != nil {
		return nil, err
	}
	if c.APIKeySigner != nil {
		if err := c.APIKeySigner.Sign(req); err != nil {
			return nil, err
		}
	}
	return req, nil
}

// HibernationGoingFinalizeTaskPipelineBasePath computes a request path to the hibernation_going_finalize_task action of PipelineBase.
func HibernationGoingFinalizeTaskPipelineBasePath(id string) string {
	param0 := id

	return fmt.Sprintf("/pipeline_bases/%s/hibernation_going_finalize_task", param0)
}

// Task to finalize hibernation_going status
func (c *Client) HibernationGoingFinalizeTaskPipelineBase(ctx context.Context, path string, error *string, operationID *string) (*http.Response, error) {
	req, err := c.NewHibernationGoingFinalizeTaskPipelineBaseRequest(ctx, path, error, operationID)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewHibernationGoingFinalizeTaskPipelineBaseRequest create the request corresponding to the hibernation_going_finalize_task action endpoint of the PipelineBase resource.
func (c *Client) NewHibernationGoingFinalizeTaskPipelineBaseRequest(ctx context.Context, path string, error *string, operationID *string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	values := u.Query()
	if error != nil {
		values.Set("error", *error)
	}
	if operationID != nil {
		values.Set("operation_id", *operationID)
	}
	u.RawQuery = values.Encode()
	req, err := http.NewRequest("PUT", u.String(), nil)
	if err != nil {
		return nil, err
	}
	if c.APIKeySigner != nil {
		if err := c.APIKeySigner.Sign(req); err != nil {
			return nil, err
		}
	}
	return req, nil
}

// ListPipelineBasePath computes a request path to the list action of PipelineBase.
func ListPipelineBasePath() string {

	return fmt.Sprintf("/pipeline_bases")
}

// list
func (c *Client) ListPipelineBase(ctx context.Context, path string, orgID string) (*http.Response, error) {
	req, err := c.NewListPipelineBaseRequest(ctx, path, orgID)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewListPipelineBaseRequest create the request corresponding to the list action endpoint of the PipelineBase resource.
func (c *Client) NewListPipelineBaseRequest(ctx context.Context, path string, orgID string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	values := u.Query()
	values.Set("org_id", orgID)
	u.RawQuery = values.Encode()
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	if c.APIKeySigner != nil {
		if err := c.APIKeySigner.Sign(req); err != nil {
			return nil, err
		}
	}
	return req, nil
}

// PullTaskPipelineBasePath computes a request path to the pull_task action of PipelineBase.
func PullTaskPipelineBasePath(id string) string {
	param0 := id

	return fmt.Sprintf("/pipeline_bases/%s/pull_task", param0)
}

// Task to pull progress messages
func (c *Client) PullTaskPipelineBase(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewPullTaskPipelineBaseRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewPullTaskPipelineBaseRequest create the request corresponding to the pull_task action endpoint of the PipelineBase resource.
func (c *Client) NewPullTaskPipelineBaseRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("PUT", u.String(), nil)
	if err != nil {
		return nil, err
	}
	if c.APIKeySigner != nil {
		if err := c.APIKeySigner.Sign(req); err != nil {
			return nil, err
		}
	}
	return req, nil
}

// ShowPipelineBasePath computes a request path to the show action of PipelineBase.
func ShowPipelineBasePath(id string) string {
	param0 := id

	return fmt.Sprintf("/pipeline_bases/%s", param0)
}

// show
func (c *Client) ShowPipelineBase(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewShowPipelineBaseRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewShowPipelineBaseRequest create the request corresponding to the show action endpoint of the PipelineBase resource.
func (c *Client) NewShowPipelineBaseRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	if c.APIKeySigner != nil {
		if err := c.APIKeySigner.Sign(req); err != nil {
			return nil, err
		}
	}
	return req, nil
}

// WakingFinalizeTaskPipelineBasePath computes a request path to the waking_finalize_task action of PipelineBase.
func WakingFinalizeTaskPipelineBasePath(id string) string {
	param0 := id

	return fmt.Sprintf("/pipeline_bases/%s/waking_finalize_task", param0)
}

// Task to finalize waking status
func (c *Client) WakingFinalizeTaskPipelineBase(ctx context.Context, path string, error *string, operationID *string) (*http.Response, error) {
	req, err := c.NewWakingFinalizeTaskPipelineBaseRequest(ctx, path, error, operationID)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewWakingFinalizeTaskPipelineBaseRequest create the request corresponding to the waking_finalize_task action endpoint of the PipelineBase resource.
func (c *Client) NewWakingFinalizeTaskPipelineBaseRequest(ctx context.Context, path string, error *string, operationID *string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	values := u.Query()
	if error != nil {
		values.Set("error", *error)
	}
	if operationID != nil {
		values.Set("operation_id", *operationID)
	}
	u.RawQuery = values.Encode()
	req, err := http.NewRequest("PUT", u.String(), nil)
	if err != nil {
		return nil, err
	}
	if c.APIKeySigner != nil {
		if err := c.APIKeySigner.Sign(req); err != nil {
			return nil, err
		}
	}
	return req, nil
}
