sudo: false
language: go
go:
  - 1.6.3
before_install:
  ## Install App Engine SDK for Go
  - curl -o $HOME/go_appengine_sdk_linux_amd64.zip https://storage.googleapis.com/appengine-sdks/featured/go_appengine_sdk_linux_amd64-1.9.48.zip
  - mkdir $HOME/go_appengine
  - unzip -q -x $HOME/go_appengine_sdk_linux_amd64.zip -d $HOME
  - PATH=$PATH:$HOME/go_appengine
  - goapp version
  ## Install glide
  - test -d $GOPATH/bin || mkdir -p $GOPATH/bin
  - make checksetup
  - curl https://glide.sh/get | sh
install:
  ## Install dependencies
  - make glide_install
script:
  - make ci
