anchors:
- &string_required
  type: string
  required: true
- &time_required
  type: time.Time
  required: true

types:
  PipelineStatus:
    base: string
    enum: "definitions/Pipeline/properties/status/enum"
  Pipeline:
    goon:
      # id_type: int64
      # id_type: string
      # id_type: UUID (type: string)
      id_type: int64
      ancestor: Organization
    # payload: PipelinePayload
    media_type: Pipeline
    fields:
      Name: *string_required
      ProjectID: *string_required
      Zone: *string_required
      InstanceGroup: InstanceGroupBody
      Container: PipelineContainer
      HibernationDelay:
        type: int
        required: true
      Status:
        type: PipelineStatus
        required: true
      IntanceGroupID: *string_required
      CreatedAt: *time_required
      UpdatedAt: *time_required
