service: concurrent-batch-agent # see https://cloud.google.com/appengine/docs/go/
runtime: go                     # see https://cloud.google.com/appengine/docs/go/
api_version: go1                # used when appengine supports different go versions

# These are specified by using command line flag
# application: my-application-id  # defined when you create your app using google dev console
# version: alpha                  # you can run multiple versions of an app and A/B test

handlers:
- url: /admin/.*
  script: _go_app
  login: admin

- url: /.*
  script: _go_app

nobuild_files:
- vendor/

skip_files:
- vendor/

env_variables:
  TRANSACTION_ATTEMPTS: '10'
